### PR TITLE
I'd like to pull your changed functions into our branch.

### PR DESCRIPTION
**Pull request by jonesor**
I've never submitted a pull request before, so fingers crossed that I am doing it right!

### CODE REVIEW

**Comment by tdjames1** [comment]
Looks like it worked? The only problem is that the issues that I've raised on the new functions remain on my fork - it would be good to transfer them.

**Comment by jonesor** [comment]
I can copy them over later today or tomorrow.

**Comment by tdjames1** [comment]
This might be useful: https://github.com/holman/ama/issues/413#issuecomment-60070074

**Comment by tdjames1** [comment]
Done. I used the github-issues-import script to import them: https://github.com/IQAndreas/github-issues-import

**Pull request merged**
